GET http://localhost:3000/api/num2

###

POST  http://localhost:3000/somar
content-type: application/json

{
    "num1": 5,
    "num2": "ads"
}

###


POST  http://localhost:3000/subtrair
content-type: application/json

{
    "num1": 11,
    "num2": "adf"
}

###

POST  http://localhost:3000/multiplicar
content-type: application/json

{
    "num1": 10,
    "num2": 2
}

###

POST  http://localhost:3000/dividir
content-type: application/json

{
    "num1": 0,
    "num2": 0
}